### ISSUE TITLE
LibCURL build fails when installed on secure networks

### ISSUE THREAD

**Issue by jlepird** [JuliaWeb/LibCURL.jl#13]
The LibCURL build currently contains a statement to download a repomd.xml file if it's not found in the cache. However, on some secure networks, direct file downloads like wget are blocked entirely. Would it be possible to incorporate this .xml file in to your git repository so that users can install from behind strict firewalls?

Below is a screenshot of the build errors.

![image](https://cloud.githubusercontent.com/assets/5903470/3092850/1b68e55a-e5ad-11e3-8c81-0505dfb4cd5f.png)

**Comment by basunh** [comment]
without LibCURL package will jupyter notebook calls julia

**Comment by omus** [comment]
WinRPM and BinDeps were dropped from this package in version v0.3.0. The switch to using artifacts in v0.6.0 should remove any remaining firewall restrictions.
