### ISSUE TITLE
`fd_set` is referenced but never defined

### ISSUE THREAD

**Issue by iamed2** [JuliaWeb/LibCURL.jl#33]
On 0.6 this causes a `UndefVarError: fd_set not defined` on load. I have no idea why it works on 0.5.

**Comment by yuyichao** [comment]
Probably because the error is raised much earlier now and no one was using `curl_multi_fdset` before.

**Comment by omus** [comment]
Defined `fd_set` in #36. I'm not 100% sure the definition is correct but at least now the package can be loaded.
