### ISSUE TITLE
Build fails on Julia 1.0

### ISSUE THREAD

**Issue by GravityAssisted** [JuliaWeb/LibCURL.jl#44]
Building LibCURL → `~/.julia/packages/LibCURL/yT2TD/deps/build.log`
┌ Error: Error building `LibCURL`: 
│ WARNING: could not import Compat.is_windows into Main
│ ERROR: LoadError: UndefVarError: is_windows not defined
│ Stacktrace:
│  [1] top-level scope at none:0
│  [2] include at ./boot.jl:317 [inlined]
│  [3] include_relative(::Module, ::String) at ./loading.jl:1038
│  [4] include(::Module, ::String) at ./sysimg.jl:29
│  [5] include(::String) at ./client.jl:388
│  [6] top-level scope at none:0
│ in expression starting at /Users/arora/.julia/packages/LibCURL/yT2TD/deps/build.jl:6
└ @ Pkg.Operations ~/src/julia/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068

**Comment by omus** [comment]
That specific error has been addressed. Currently Julia 1.0 on Windows isn't working. Hopefully, we can get the binary builder setup working and resolve that last thing.

**Comment by adamryczkowski** [comment]
This package is broken with the same error message on Linux, too. Tested on Ubuntu 16.04 and 18.04 using both Julia 1.0 and the current master branch (that describes itself as Julia 1.1).

**Comment by ararslan** [comment]
Fixed by #46
