### ISSUE TITLE
Use the artifact system or the Julia provided libcurl

### ISSUE THREAD

**Issue by ViralBShah** [JuliaWeb/LibCURL.jl#77]
In a [move towards artifacts](https://github.com/JuliaPackaging/Yggdrasil/issues/653), I am wondering if this package can move away from BinaryProvider.

Should this package rely on `libcurl ` that ships with Julia?

**Comment by omus** [comment]
I attempted to use LibCURL_jll in https://github.com/JuliaWeb/LibCURL.jl/pull/75 but there was an unexpected error. Probably we could use the `libcurl` that ships with Julia

**Comment by ViralBShah** [comment]
Maybe just wait for stdlibs using jlls?

**Comment by aviks** [comment]
>Probably we could use the libcurl that ships with Julia

Libcurl ships with Julia only on Linux I believe. I think #78 should fix the SSL issues.

**Comment by omus** [comment]
Fixed with the merging of #75
