### ISSUE TITLE
Update to  7.71.1

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaWeb/LibCURL.jl#85]
I notice LibCURL_jll.jl is outdated too, and the project file here doesn't even point to the version there.

[I just saw PHP was updated because of security issue in libcurl.]

Should this be reported at LibCURL_jll.j and/or Julia?

I can't see where the version number is otherwise, so not sure how to make a PR.

**Comment by omus** [comment]
Most of the *_jll packages are generated from https://github.com/JuliaPackaging/Yggdrasil. Specifically you should be able to update https://github.com/JuliaPackaging/Yggdrasil/blob/master/L/LibCURL/build_tarballs.jl to use the latest LibCURL version and make PR.

**Comment by PallHaraldsson** [comment]
I made a PR.

**Comment by omus** [comment]
https://github.com/JuliaPackaging/Yggdrasil/pull/1312

**Comment by PallHaraldsson** [comment]
The PR was merged, but there seems something more needs to be done here; and also for certs. And tag a new version.

**Comment by omus** [comment]
LibCURL will automatically use the new LibCURL_jll and this package switched to the separate cert package with the last minor release
```julia
(LibCURL) pkg> add LibCURL
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `/tmp/LibCURL/Project.toml`
  [b27032c2] + LibCURL v0.6.1
  Updating `/tmp/LibCURL/Manifest.toml`
  [b27032c2] + LibCURL v0.6.1
  [deac9b47] + LibCURL_jll v7.71.1+0
  [29816b5a] + LibSSH2_jll v1.9.0+3
  [c8ffd9c3] + MbedTLS_jll v2.16.6+1
  [14a3606d] + MozillaCACerts_jll v2020.0.0-01-01+0
  [83775a58] + Zlib_jll v1.2.11+14
  [8e850ede] + nghttp2_jll v1.40.0+2
  [2a0f44e3] + Base64 
  [ade2ca70] + Dates 
  [8ba89e20] + Distributed 
  [b77e0a4c] + InteractiveUtils 
  [76f85450] + LibGit2 
  [8f399da3] + Libdl 
  [56ddb016] + Logging 
  [d6f4376e] + Markdown 
  [44cfe95a] + Pkg 
  [de0858da] + Printf 
  [3fa0cd96] + REPL 
  [9a3f8284] + Random 
  [ea8e919c] + SHA 
  [9e88b42a] + Serialization 
  [6462fe0b] + Sockets 
  [8dfed614] + Test 
  [cf7118a7] + UUIDs 
  [4ec0a83e] + Unicode
```
