### ISSUE TITLE
Usage example for curl_multi_perform

### ISSUE THREAD

**Issue by szafna** [JuliaWeb/LibCURL.jl#86]
It would be nice if you could provide usage example for curl_multi perform.

**Comment by StefanKarpinski** [comment]
This is quite tricky to implement correctly. I've got a working usage of it that will be the basis for downloading things in Julia 1.6: https://github.com/StefanKarpinski/Downloader.jl.

**Comment by szafna** [comment]
Will try with Donloader.jl

**Comment by StefanKarpinski** [comment]
It's not intended for public usage at the moment: there are no releases and the API will definitely break before there are. However, it does serve as an example of how to use the multi socket API from Julia.

**Comment by szafna** [comment]
Ok.
